Repository acm-ucr/gardening-website, pull requests merged in 2024-08, with the labels that each got.

#64 hyperlink the contacts in footer
  src/components/Footer.jsx
Labels: enhancement, Ready For Review

#65 Added title and some elements
  src/components/home/Hero.jsx
Labels: Ready For Review

#79 made directions title responsive
  src/components/home/Directions.jsx
Labels: help wanted, home, Ready For Review, responsiveness

#80 Tips Responsiveness
  src/components/home/Tips.jsx
Labels: Ready For Review

#81 fixed Upcoming events page
  src/components/events/Upcoming.jsx
Labels: board, Ready For Review

#85 Adjusted margins and text responsiveness
  src/components/home/Values.jsx
Labels: Ready For Review

#86 Fixed Calendar style
  src/components/events/CalendarEvents.jsx
  src/components/events/CustomEvents.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/index.css
Labels: Ready For Review

#84 Fixed responsiveness, cards, bugs
  src/components/board/Board.jsx
  src/components/board/Card.jsx
  src/components/board/Title.jsx
  src/components/events/CalendarEvents.jsx
  src/components/gallery/Photos.jsx
Labels: ready to merge, board, Ready For Review, responsiveness

#94 made changes to footer for responsiveness
  src/components/Footer.jsx
Labels: Ready For Review, responsiveness

#95 rounded corners, fixed colors, rotated more, reduced space
  src/components/home/Values.jsx
  tailwind.config.js
Labels: Ready For Review

#96 Hidden scrollbar
  src/app/globals.css
Labels: Ready For Review

#101 Made icons and links blue when hovered
  src/components/Footer.jsx
Labels: Ready For Review

#98 why join responsive section completed
  src/components/home/WhyJoin.jsx
Labels: home, Ready For Review, responsiveness

#82 Progress for navbar collapse, all tabs visible for smaller windows
  src/app/layout.js
  src/components/Navigation.jsx
Labels: help wanted

#114 complete fix of Calendar
  src/app/layout.js
  src/components/Navigation.jsx
  src/components/events/CalendarEvents.jsx
  src/components/events/CustomEventWrapper.jsx
  src/components/events/CustomEvents.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/Modal.js
  src/components/events/Modals.jsx
  src/components/events/index.css
  tailwind.config.js
Labels: Ready For Review

#117 fixed gallary for responsiveness
  src/components/gallery/Photos.jsx
Labels: gallery, Ready For Review

#113 changed the title size in value section
  src/components/home/Values.jsx
Labels: home, Ready For Review
