Repository acm-ucr/gardening-website, pull requests merged in 2024-07, with the labels that each got.

#29 Navigation bar progess
  package-lock.json
  package.json
  src/app/layout.js
  src/components/Navbar.jsx
  src/components/Navigation.jsx
Labels: help wanted, do not merge

#27 why join? section made
  src/components/home/Join.jsx
  src/components/home/WhyJoin.jsx
Labels: good first issue, Ready For Review

#24 Tips Page
  src/components/Navbar.jsx
  src/components/Navigation.jsx
  src/components/home/Tips.jsx
  src/components/home/WhyJoin.jsx
  tailwind.config.js
Labels: good first issue

#23 made values text on home screen
  src/app/layout.js
  src/components/Navigation.jsx
  src/components/home/Tips.jsx
  src/components/home/Values.jsx
  tailwind.config.js
Labels: good first issue

#25 Direction page made
  src/components/home/Directions.jsx
  tailwind.config.js
Labels: Ready For Review

#26 Added Footer
  package-lock.json
  package.json
  src/components/Footer.jsx
Labels: Ready For Review

#47 404 page
  package-lock.json
  src/app/layout.js
  src/app/not-found.js
Labels: Ready For Review

#46 added group picture
  src/components/board/GroupPic.jsx
Labels: board, Ready For Review

#45 Created 3x3 grid for scrapbook
  package-lock.json
  public/catOrangeGardening.webp
  src/app/gallery/page.js
Labels: Ready For Review

#40 Finished Join Gardening Text
  src/components/home/Join.jsx
Labels: Ready For Review

#44 Added section cards and labels
  src/components/home/Values.jsx
Labels: help wanted

#59 added empty box and plant to join section
  src/components/home/Join.jsx
Labels: home, Ready For Review

#61 added upcoming events to event page
  src/app/events/page.js
Labels: calendar, Ready For Review

#63 Sangha0822/board grids
  src/app/board/page.js
  src/components/board/Board.jsx
  src/components/board/Card.jsx
  src/data/board.js
Labels: board, Ready For Review

#62 Fixed the small screen responsiveness
  src/components/home/WhyJoin.jsx
Labels: Ready For Review, responsiveness

#67 Join Gardening Text Responsiveness
  src/components/home/Join.jsx
Labels: responsiveness

#66 Created red circles and empty div
  src/components/Navbar.jsx
  src/components/home/Hero.jsx
Labels: home

#60 semicircle made but needs fixing
  src/app/board/page.js
  src/components/Navigation.jsx
  src/components/board/Board.jsx
  src/components/board/Title.jsx
  tailwind.config.js
Labels: help wanted, board, Ready For Review

#70 added calendar component
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/events/CalendarEvents.jsx
  src/components/events/CustomEvents.jsx
  src/components/events/CustomHeader.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/Modal.jsx
Labels: calendar
